[tool.poetry]
name = "Sportstradamus"
version = "1.1.1"
description = "Scrape Sportsbooks Odds and Player Stats and export to Google Sheets"
authors = ["Trevor Jerome <trevor81994@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/tjjerome/sportstradamus"
repository = "https://github.com/tjjerome/sportstradamus"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
python-snappy = "^0.6.1"
google-auth-oauthlib = ">=1.0.0"
gspread = ">=5.8.0"
mlb-statsapi = ">=1.6.1"
nba-api = ">=1.2"
nfl-data-py = ">=0.3.0"
numpy = ">=1.24.3"
pandas = ">=2.0.1"
protobuf = ">=4.23.0"
requests = ">=2.30.0"
scipy = ">=1.10.1"
scrapeops-python-requests = ">=0.4.7"
tqdm = ">=4.65.0"
importlib = "^1.0.4"
click = "^8.1.3"
pytz = "^2023.3"
scikit-learn = "^1.2.2"
scikit-optimize = "^0.9.0"
sphinx-pdj-theme = "^0.4.0"
sphinx-pyproject = "^0.1.0"
lightgbm = "^3.3.5"
pytest = "^7.3.2"

[tool.poetry.scripts]
prophecize = "sportstradamus.sportstradamus:main"
get-money = "sportstradamus.moneylines:get_moneylines"
meditate = "sportstradamus.train:meditate"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"